name: Build and Deploy to staging
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - deploy/staging
jobs:
  build-assets:
    environment: staging
    uses: ./.github/jobs/build.yml
  push-to-cloudways:
    environment: staging
    name: Push change to Cloudways
    run: |
      echo "Test Push"
