name: Build and Deploy to staging
run-name: Deploy to staging (Initiated by ${{ github.actor }})
on:
  push:
    branches:
      - deploy/staging
jobs:
  deployment:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Assets
        uses: ./.github/actions/build-assets
        with:
          theme-path: ${{ vars.THEME_PATH }}
          target-branch: "actions/deployment-staging"
      - name: Cloudways deployment
        uses: ./.github/actions/cloudways-pull
        with:
          target-branch: "actions/deployment-staging"
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          server-id: ${{ env.CLOUDWAYS_SERVER_ID }}
          application-id: ${{ env.CLOUDWAYS_APP_ID }}
