name: Build and Deploy to staging
run-name: Deploy to staging (Initiated by ${{ github.actor }})
on:
  push:
    branches:
      - deploy/staging
      - develop
jobs:
  build:
    uses: ./.github/workflows/jobs-build.yml
    with:
      theme-path: ${{ vars.THEME_PATH }}
  deployment:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push to Cloudways
        run: |
          ls
          echo "Test Push"
