name: Build and Deploy to production
run-name: Deploy to production (Initiated by ${{ github.actor }})
on:
  push:
    branches:
      - deploy/production
jobs:
  deployment:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Assets
        uses: ./.github/actions/build-assets
        with:
          theme-path: ${{ vars.THEME_PATH }}
          target-branch: "actions/deployment-production"
      - name: Push to Cloudways
        uses: ./.github/actions/cloudways-pull
        with:
          target-branch: "actions/deployment-staging"
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          server-id: ${{ vars.CLOUDWAYS_SERVER_ID }}
          application-id: ${{ vars.CLOUDWAYS_APP_ID }}
