name: Build and Deploy to staging
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - deploy/staging
      - develop
jobs:
  deployment:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Build Assets
        uses: ./.github/workflows/jobs-build.yml
      - name: Push to CLoudways
        run: |
          ls
          echo "Test Push"
